version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
    - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "dist/**/*"
    - "node_modules/**/*"